"""
PySide stub files generated by **IceSpringPySideStubs**

Home: https://baijifeilong.github.io/2022/01/06/ice-spring-pyside-stubs/index.html

Github: https://github.com/baijifeilong/IceSpringPySideStubs

PyPI(PySide2): https://pypi.org/project/IceSpringPySideStubs-PySide2

PyPI(PySide6): https://pypi.org/project/IceSpringPySideStubs-PySide6

PyPI(PyQt5): https://pypi.org/project/IceSpringPySideStubs-PyQt5

PyPI(PyQt6): https://pypi.org/project/IceSpringPySideStubs-PyQt6

Generated by BaiJiFeiLong@gmail.com

License: MIT
"""
"""
This file contains the exact signatures for all functions in module
PySide6.QtBluetooth, except for defaults which are replaced by "...".
"""
from __future__ import annotations

from enum import IntFlag
from typing import overload

import PySide6.QtBluetooth
import PySide6.QtCore

class QBluetooth:
    """
    https://doc.qt.io/qt-6/qbluetooth.html

    **Detailed Description**
    """

    class AttAccessConstraint(IntFlag):
        AttAuthorizationRequired: QBluetooth.AttAccessConstraint = ...
        AttAuthenticationRequired: QBluetooth.AttAccessConstraint = ...
        AttEncryptionRequired: QBluetooth.AttAccessConstraint = ...

    class AttAccessConstraints: ...

    class Security(IntFlag):
        NoSecurity: QBluetooth.Security = ...
        Authorization: QBluetooth.Security = ...
        Authentication: QBluetooth.Security = ...
        Encryption: QBluetooth.Security = ...
        Secure: QBluetooth.Security = ...

    class SecurityFlags: ...

    @overload
    @staticmethod
    def qt_getEnumMetaObject(
        arg__1: PySide6.QtBluetooth.QBluetooth.AttAccessConstraint,
    ) -> PySide6.QtCore.QMetaObject: ...
    @overload
    @staticmethod
    def qt_getEnumMetaObject(
        arg__1: PySide6.QtBluetooth.QBluetooth.Security,
    ) -> PySide6.QtCore.QMetaObject: ...
    @overload
    @staticmethod
    def qt_getEnumName(
        arg__1: PySide6.QtBluetooth.QBluetooth.AttAccessConstraint,
    ) -> bytes: ...
    @overload
    @staticmethod
    def qt_getEnumName(arg__1: PySide6.QtBluetooth.QBluetooth.Security) -> bytes: ...
