fail_fast: true
repos:
  # `commitlint` is only available through npm (Node.js), not pip (PyPI).
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.19.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ["--config=commitlint.config.js"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
        name: (pre-commit-hooks) Check docstrings defined before code
      - id: name-tests-test
        name: (pre-commit-hooks) Check tests named correctly ('test_*.py')
        args: [
            "--django", # `test_*.py` style
          ]
      - id: check-merge-conflict
        name: (pre-commit-hooks) Check no files contain merge conflict strings
      - id: check-toml
        name: (pre-commit-hooks) Check TOML files parseable
      - id: check-yaml
        name: (pre-commit-hooks) Check YAML files parseable

  # `markdownlint` is only available through npm (Node.js), not pip (PyPI).
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: (markdownlint) Check Markdown syntax
        args: ["--config=.markdownlint.yml"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.27.3
    hooks:
      - id: typos
        name: (typos) Check for typos (misspellings)

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        name: (check-json5) Check JSON5 files parseable (json5 = json with comments)

  - repo: local
    hooks:
      - id: mypy
        name: (mypy) Check static type hinting
        entry: mypy
        language: system
        types: [python]
        require_serial: true
