from __future__ import annotations

from collections.abc import Generator

from _typeshed import Incomplete

def qapp_args(): ...
def qapp(qapp_args, pytestconfig): ...
def qtbot(qapp, request): ...
def qtlog(request): ...
def qtmodeltester(request) -> Generator[Incomplete, None, None]: ...
def pytest_addoption(parser) -> None: ...
def pytest_runtest_setup(item) -> Generator[None, None, None]: ...
def pytest_runtest_call(item) -> Generator[None, None, None]: ...
def pytest_runtest_teardown(item) -> Generator[None, None, None]: ...
def pytest_configure(config) -> None: ...
def pytest_report_header(): ...
